include "application.conf"

application {
    profile = PROD
    bestillingOrgnr = "995277670"
}

mq {
    hostname = "mpls02.adeo.no"
    port = 1414
    queueManagerName = "MPLS02"
    channelName = "P_SKATTEKORT"
    fraForSystemQueue = "QA.P_SKATTEKORT.FRA_FORSYSTEM"
    leveransekoeOppdragZSkattekort = "QA.P231.OB04_SKATTEKORT"
    leveransekoeOppdragZSkattekortStor = "QA.P231.OB04_SKATTEKORT_STOR"
}

maskinporten {
    systemBrukerClaim = "995277670"
}

skatteetaten {
    skatteetatenUrl = "https://api.skatteetaten.no"
}

pdl {
    pdlUrl = "https://pdl-api.prod-fss-pub.nais.io"
    pdlScope = "api://prod-fss.pdl.pdl-api/.default"
}

tilgangsmaskin {
    tilgangsmaskinUrl = "http://populasjonstilgangskontroll.tilgangsmaskin"
    tilgangsmaskinScope = "api://prod-gcp.tilgangsmaskin.populasjonstilgangskontroll/.default"
}
