include "application-dev.conf"
include file("defaults.properties")

application {
    profile = LOCAL
}

kafka {
    enabled = false
}

tilgangsmaskin {
    tilgangsmaskinUrl = "https://tilgangsmaskin.intern.dev.nav.no"
}

darePoc {
    darePocUrl = "https://sokos-dare-poc.intern.dev.nav.no"
}