include "application.conf"

ktor {
    environment = dev
}

application {
    profile = DEV
    gyldigeFnr = "KUNSTIGE_FNR"
}

mq {
    hostname = "mqls02.preprod.local"
    port = 1413
    mqQueueManagerName = "MQLS02"
    mqChannelName = "Q2_SKATTEKORT"
    fraForSystemQueue = "QA.Q2_SKATTEKORT.FRA_FORSYSTEM"
    leveransekoeOppdragZSkattekort = "QA.Q2_231.OB04_SKATTEKORT"
    leveransekoeOppdragZSkattekortStor = "QA.Q2_231.OB04_SKATTEKORT_STOR"
}

maskinporten {
    systemBrukerClaim = "312978083"
}

skatteetaten {
    skatteetatenUrl = "https://api-test.sits.no"
}

pdl {
    pdlUrl = "https://pdl-api.dev-fss-pub.nais.io"
    pdlScope = "api://dev-fss.pdl.pdl-api/.default"
}

tilgangsmaskin {
    tilgangsmaskinUrl = "http://populasjonstilgangskontroll.tilgangsmaskin"
    tilgangsmaskinScope = "api://dev-gcp.tilgangsmaskin.populasjonstilgangskontroll/.default"
}

darePoc {
    darePocUrl = "http://sokos-dare-poc"
    darePocScope = "api://dev-gcp.okonomi.sokos-dare-poc/.default"
}
