include "application-dev.conf"
include file("defaults.properties")

application {
    appName = "sokos-skattekort"
    bestillingOrgnr = "312978083"
    gyldigeFnr = "ALLE"
    mqListenerEnabled = true
    podName = "notinnais"
    profile = LOCAL
}

darePoc {
    darePocScope = ${?DAREPOC_SCOPE}
    darePocUrl = "https://sokos-dare-poc.intern.dev.nav.no"
}

kafka {
    enabled = false
    brokers = ""
    schemaRegistry = ""
    schemaRegistryUser = ""
    schemaRegistryPassword = ""
    truststorePath = ""
    credstorePassword = ""
    keystorePath = ""
}

maskinporten {
    clientId = ${?MASKINPORTEN_CLIENT_ID}
    wellKnownUrl = ${?MASKINPORTEN_WELL_KNOWN_URL}
    rsaKeyString = ${?MASKINPORTEN_CLIENT_JWK}
    scopes = ${?MASKINPORTEN_SCOPES}
    systemBrukerClaim = ${?MASKINPORTEN_SYSTEM_BRUKER_CLAIM}
}

mq {
    hostname = ${?MQ_HOSTNAME}
    port = ${?MQ_PORT}
    queueManagerName = ${?MQ_QUEUE_MANAGER_NAME}
    channelName = ${?MQ_CHANNEL_NAME}
    serviceUsername = ${?MQ_SERVICE_USERNAME}
    servicePassword = ${?MQ_SERVICE_PASSWORD}
    userAuth = true
    fraForSystemQueue = ${?MQ_FRA_FORSYSTEM_QUEUE_NAME}
    leveransekoeOppdragZSkattekort = ${?MQ_LEVERANSEKOE_OPPDRAGZ_SKATTEKORT}
    leveransekoeOppdragZSkattekortStor = ${?MQ_LEVERANSEKOE_OPPDRAGZ_SKATTEKORT_STOR}
}

pdl {
    jdbcUrl = ${?DB_JDBC_URL}
    password = ${?DB_PASSWORD}
    pdlScope = ${?PDL_SCOPE}
    pdlUrl = ${?PDL_URL}
    username = ${?DB_USERNAME}
}

postgres {
  host = "localhost"
  port = "5432"
}

tilgangsmaskin {
    tilgangsmaskinUrl = "https://tilgangsmaskin.intern.dev.nav.no"
}

