include "application.conf"

application {
    profile = TEST
    gyldigeFnr = "ALLE"
    bestillingOrgnr = "312978083"
    mqListenerEnabled = true
}


azureAd {
    clientId = "azure_app_client_id"
    wellKnownUrl = "azure_app_well_known_url"
    tenantId = "azure_app_tenant_id"
    clientSecret = "azure_app_client_secret"
    providerName = "default"
}

postgres {
    jdbcUrl = "postgres_jdbc_url"
    name = "sokos-skattekort"
    host = "localhost"
    port = "5432"
    username = "sokos-skattekort"
    password = "sokos-skattekort-password"
}

mq {
    hostname = "localhost"
    port = 0
    queueManagerName = "test_queue_manager"
    channelName = "test_channel"
    serviceUsername = "mq_username"
    servicePassword = "mq_password"
    userAuth = true
    fraForSystemQueue = "FRA_FORSYSTEM"
    leveransekoeOppdragZSkattekort = "TIL_OS"
    leveransekoeOppdragZSkattekortStor = "TIL_OS_STOR"
}

kafka {
    enabled = false
    brokers = ""
    schemaRegistry = ""
    schemaRegistryUser = ""
    schemaRegistryPassword = ""
    truststorePath = ""
    credstorePassword = ""
    keystorePath = ""
}

unleash {
  unleashApi = ""
  apiKey = ""
  environment = ""
}

skatteetaten {
  skatteetatenUrl = ""
}

darePoc {
  darePocUrl = ""
  darePocScope = ""
}
