include "application-dev.conf"

ENVIRONMENT = LOCAL

#Postgres
DB_DATABASE = "sokos-skattekort"
DB_HOST = "localhost"
DB_PORT = "5432"

#KAFKA
KAFKA_CONSUMER_ENABLED = "false"

#TILGANGSMASKIN
TILGANGSMASKIN_URL = "https://tilgangsmaskin.intern.dev.nav.no"

#DAREPOC
DAREPOC_URL = "https://sokos-dare-poc.intern.dev.nav.no"