include "application.conf"

ENVIRONMENT = Q1

GYLDIGE_FNR = "KUNSTIGE_FNR"

#MQ
MQ_HOSTNAME = "mqls02.preprod.local"
MQ_PORT = "1413"
MQ_QUEUE_MANAGER_NAME = "MQLS02"
MQ_CHANNEL_NAME = "Q1_SKATTEKORT"
MQ_FRA_FORSYSTEM_QUEUE_NAME = "QA.Q1_SKATTEKORT.FRA_FORSYSTEM"
MQ_LEVERANSEKOE_OPPDRAGZ_SKATTEKORT = "QA.Q1_231.OB04_SKATTEKORT"
MQ_LEVERANSEKOE_OPPDRAGZ_SKATTEKORT_STOR = "QA.Q1_231.OB04_SKATTEKORT_STOR"

#MASKINPORTEN
MASKINPORTEN_SYSTEM_BRUKER_CLAIM = "312978083"

#SKATTEETATEN
SKATTEETATEN_API_URL = "https://api-test.sits.no"

#PDL
PDL_URL = "https://pdl-api-q1.dev-fss-pub.nais.io"
PDL_SCOPE = "api://dev-fss.pdl.pdl-api-q1/.default"

#TILGANGSMASKIN
TILGANGSMASKIN_URL = "http://populasjonstilgangskontroll.tilgangsmaskin"
TILGANGSMASKIN_SCOPE = "api://dev-gcp.tilgangsmaskin.populasjonstilgangskontroll/.default"

#DAREPOC
DAREPOC_URL = "http://sokos-dare-poc"
DAREPOC_SCOPE = "api://dev-gcp.okonomi.sokos-dare-poc/.default"