include file("defaults.properties")

ktor {
    environment = local
}

application {
    profile = LOCAL
    appName = "sokos-skattekort"
    appName = ${?NAIS_APP_NAME}
    namespace = "okonomi"
    podName = "notinnais"
    podName = ${?NAIS_POD_NAME}
    gyldigeFnr = "ALLE"
    gyldigeFnr = ${?GYLDIGE_FNR}
    bestillingOrgnr = "312978083"
    mqListenerEnabled = true
}

azureAd {
    clientId = ${?AZURE_APP_CLIENT_ID}
    wellKnownUrl = ${?AZURE_APP_WELL_KNOWN_URL}
    tenantId = ${?AZURE_APP_TENANT_ID}
    clientSecret = ${?AZURE_APP_CLIENT_SECRET}
    providerName = "azureAd"
}

postgres {
    jdbcUrl = ${?DB_JDBC_URL}
    name = ${?DB_DATABASE}
    host = ${?DB_HOST}
    port = ${?DB_PORT}
    username = ${?DB_USERNAME}
    password = ${?DB_PASSWORD}
}

mq {
    hostname = ${?MQ_HOSTNAME}
    port = ${?MQ_PORT}
    mqQueueManagerName = ${?MQ_QUEUE_MANAGER_NAME}
    mqChannelName = ${?MQ_CHANNEL_NAME}
    serviceUsername = ${?MQ_SERVICE_USERNAME}
    servicePassword = ${?MQ_SERVICE_PASSWORD}
    userAuth = true
    fraForSystemQueue = ${?MQ_FRA_FORSYSTEM_QUEUE_NAME}
    leveransekoeOppdragZSkattekort = ${?MQ_LEVERANSEKOE_OPPDRAGZ_SKATTEKORT}
    leveransekoeOppdragZSkattekortStor = ${?MQ_LEVERANSEKOE_OPPDRAGZ_SKATTEKORT_STOR}
}

scheduler {
    enabled = true
    cronBestilling = "*/5 * * * * *"
    cronUtsending = "20 * * * * *"
    cronHentSkattekort = "10 * * * * *"
    cronHentOppdaterte = "45 */1 * * * *"
    cronFetchMetrics = "50 0/10 * * * *"
    cronForespoerselInput = "55 0/5 * * * *"
    cronDeleteSkattekort = "0 0 0 15 1 *"
}

maskinporten {
    clientId = ${?MASKINPORTEN_CLIENT_ID}
    wellKnownUrl = ${?MASKINPORTEN_WELL_KNOWN_URL}
    rsaKeyString = ${?MASKINPORTEN_CLIENT_JWK}
    scopes = ${?MASKINPORTEN_SCOPES}
    systemBrukerClaim = ${?MASKINPORTEN_SYSTEM_BRUKER_CLAIM}
}

skatteetaten {
    skatteetatenUrl = ${?SKATTEETATEN_API_URL}
}

darePoc {
    darePocUrl = ${?DAREPOC_URL}
    darePocScope = ${?DAREPOC_SCOPE}
}

kafka {
    enabled = true
    topic = "pdl.leesah-v1"
    consumerGroupId = "sokos-skattekort-group-id"
    offsetReset = "earliest"
    brokers = ${?KAFKA_BROKERS}
    schemaRegistry = ${?KAFKA_SCHEMA_REGISTRY}
    schemaRegistryUser = ${?KAFKA_SCHEMA_REGISTRY_USER}
    schemaRegistryPassword = ${?KAFKA_SCHEMA_REGISTRY_PASSWORD}
    truststorePath = ${?KAFKA_TRUSTSTORE_PATH}
    credstorePassword = ${?KAFKA_CREDSTORE_PASSWORD}
    keystorePath = ${?KAFKA_KEYSTORE_PATH}
}

pdl {
    pdlUrl = ${?PDL_URL}
    pdlScope = ${?PDL_SCOPE}
}

tilgangsmaskin {
    tilgangsmaskinUrl = ${?TILGANGSMASKIN_URL}
    tilgangsmaskinScope = ${?TILGANGSMASKIN_SCOPE}
}

unleash {
    unleashApi = ${?UNLEASH_SERVER_API_URL}
    apiKey = ${?UNLEASH_SERVER_API_TOKEN}
    environment = ${?UNLEASH_SERVER_API_ENV}
}
