include "application.conf"

application {
    appName = "sokos-skattekort"
    bestillingOrgnr = "995277670"
    gyldigeFnr = "GYLDIGE"
    mqListenerEnabled = true
    podName = ${?NAIS_POD_NAME}
    profile = PROD
}


azureAd {
    clientId = ${?AZURE_APP_CLIENT_ID}
    clientSecret = ${?AZURE_APP_CLIENT_SECRET}
    providerName = "azureAd"
    tenantId = ${?AZURE_APP_TENANT_ID}
    wellKnownUrl = ${?AZURE_APP_WELL_KNOWN_URL}
}

darePoc {
    darePocUrl = ${?DAREPOC_URL}
    darePocScope = ${?DAREPOC_SCOPE}
}

kafka {
    brokers = ${?KAFKA_BROKERS}
    consumerGroupId = "sokos-skattekort-group-id"
    credstorePassword = ${?KAFKA_CREDSTORE_PASSWORD}
    enabled = true
    keystorePath = ${?KAFKA_KEYSTORE_PATH}
    offsetReset = "earliest"
    schemaRegistry = ${?KAFKA_SCHEMA_REGISTRY}
    schemaRegistryPassword = ${?KAFKA_SCHEMA_REGISTRY_PASSWORD}
    schemaRegistryUser = ${?KAFKA_SCHEMA_REGISTRY_USER}
    topic = "pdl.leesah-v1"
    truststorePath = ${?KAFKA_TRUSTSTORE_PATH}
}

maskinporten {
    clientId = ${?MASKINPORTEN_CLIENT_ID}
    wellKnownUrl = ${?MASKINPORTEN_WELL_KNOWN_URL}
    rsaKeyString = ${?MASKINPORTEN_CLIENT_JWK}
    scopes = ${?MASKINPORTEN_SCOPES}
    systemBrukerClaim = "995277670"
}

mq {
    channelName = "P_SKATTEKORT"
    fraForSystemQueue = "QA.P_SKATTEKORT.FRA_FORSYSTEM"
    hostname = "mpls02.adeo.no"
    leveransekoeOppdragZSkattekort = "QA.P231.OB04_SKATTEKORT"
    leveransekoeOppdragZSkattekortStor = "QA.P231.OB04_SKATTEKORT_STOR"
    port = 1414
    queueManagerName = "MPLS02"
    servicePassword = ${?MQ_SERVICE_PASSWORD}
    serviceUsername = ${?MQ_SERVICE_USERNAME}
    userAuth = true
}

pdl {
    pdlScope = "api://prod-fss.pdl.pdl-api/.default"
    pdlUrl = "https://pdl-api.prod-fss-pub.nais.io"
}

postgres {
    jdbcUrl = ${?DB_JDBC_URL}
    name = ${?DB_DATABASE}
    host = ${?DB_HOST}
    port = ${?DB_PORT}
    username = ${?DB_USERNAME}
    password = ${?DB_PASSWORD}
}

scheduler {
    cronBestilling = "*/5 * * * * *"
    cronDeleteSkattekort = "0 0 0 15 1 *"
    cronFetchMetrics = "50 0/10 * * * *"
    cronHentOppdaterte = "45 */30 * * * *"
    cronHentSkattekort = "10 * * * * *"
    cronUtsending = "20 * * * * *"
    enabled = true
}

skatteetaten {
    skatteetatenUrl = "https://api.skatteetaten.no"
}


tilgangsmaskin {
    tilgangsmaskinScope = "api://prod-gcp.tilgangsmaskin.populasjonstilgangskontroll/.default"
    tilgangsmaskinUrl = "http://populasjonstilgangskontroll.tilgangsmaskin"
}

unleash {
    apiKey = ${?UNLEASH_SERVER_API_TOKEN}
    environment = ${?UNLEASH_SERVER_API_ENV}
    unleashApi = ${?UNLEASH_SERVER_API_URL}
}