package no.nav.sokos.skattekort.util

import javax.sql.DataSource

import kotlin.reflect.full.memberProperties

import kotliquery.Session
import kotliquery.TransactionalSession
import kotliquery.sessionOf
import kotliquery.using

object SQLUtils {
    inline fun <reified T : Any> T.asMap(): Map<String, Any?> {
        val props = T::class.memberProperties.associateBy { it.name }
        return props.keys.associateWith { props[it]?.get(this) }
    }

    inline fun <reified T : Any> DataSource.withTx(
        existing: TransactionalSession?,
        crossinline action: (TransactionalSession) -> T,
    ): T =
        if (existing != null) {
            action(existing)
        } else {
            this.transaction { action(it) }
        }

    fun <A> DataSource.transaction(operation: (TransactionalSession) -> A): A =
        using(sessionOf(this, returnGeneratedKey = true)) { session ->
            session.transaction { tx ->
                operation(tx)
            }
        }

    suspend fun <A> DataSource.suspendTransaction(operation: suspend (TransactionalSession) -> A): A =
        sessionOf(this, returnGeneratedKey = true).use { session ->
            session.suspendTransaction { tx ->
                operation(tx)
            }
        }

    private suspend inline fun <A> Session.suspendTransaction(operation: suspend (TransactionalSession) -> A): A {
        var shouldCommit = true
        try {
            connection.begin()
            transactional = true
            val tx = TransactionalSession(connection, returnGeneratedKeys, autoGeneratedKeys, strict)
            return operation.invoke(tx)
        } catch (e: Exception) {
            shouldCommit = false
            connection.rollback()
            throw e
        } finally {
            if (shouldCommit) {
                connection.commit()
            }
            transactional = false
        }
    }
}
