apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-skattekort
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://sokos-skattekort.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: sokos-up-skattekort-ssr
          namespace: okonomi
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: okonomi-unleash-api.nav.cloud.nais.io
        - host: b27apvl219.preprod.local
          ports:
            - port: 1413
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:skattekorttilarbeidsgiver"
        - name: "altinn:authentication/systemregister.write"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        autoBackupHour: 3
        tier: db-custom-1-3840
        databases:
          - name: sokos-skattekort
            envVarPrefix: DB
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
          - name: "cloudsql.logical_decoding"
            value: "on"
  envFrom:
    - secret: sokos-skattekort-mq-credentials
    - secret: sokos-skattekort-unleash-api-token

  env:
    - name: APPLICATION_ENV
      value: DEV

