SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS person (
                                      id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                      flagget                   BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS person_offnr (
                                            id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            person_id                 BIGINT NOT NULL REFERENCES person(id) DEFERRABLE NOT NULL,
                                            gjelder_fom               DATE NOT NULL DEFAULT now(),
                                            fnr                       TEXT NOT NULL -- fødelsnummer/personIdent, ...
);

CREATE TABLE IF NOT EXISTS person_audit (
                                            id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            person_id                 BIGINT NOT NULL REFERENCES person(id) DEFERRABLE NOT NULL,
                                            bruker_id                 TEXT NOT NULL, -- bruker eller system som gjør endringen
                                            opprettet                 TIMESTAMPTZ NOT NULL DEFAULT now(),
                                            tag                       TEXT NULL, -- maskinlesbar tag for å kunne filtrere i visning av auditlogg, type "MOTTATT_BESTILLING"
                                            informasjon               TEXT NOT NULL /* menneske-lesbar informasjon om hva slags endring som blir gjort. eks:
                                              endret fødselsnummer, nytt fødselsnummer gyldig fra <dato>
                                              aktør opprettet, årsak ...
                                              aktør merket for sletting ved <dato>, årsak ...
                                              skattekort sendt arena ..
                                              */
);

CREATE INDEX IF NOT EXISTS person_offnr_person_id ON person_offnr (person_id);
CREATE INDEX IF NOT EXISTS person_audit_person_id ON person_audit (person_id);
