SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS aktoer (
                                      id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                      navn                      TEXT NOT NULL, -- menneske-lesbar representasjon av aktøren
                                      skjermet                  BOOLEAN NOT NULL, -- kode 6/7, skal ikke vises til hvemsomhelst
                                      ansatt                    BOOLEAN NOT NULL -- ansatte skal ikke nødvendigvis vises
);

CREATE TABLE IF NOT EXISTS aktoer_offnr (
                                            id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            aktoer_id                 BIGINT NOT NULL REFERENCES aktoer(id) DEFERRABLE NOT NULL,
                                            lopenr                    INTEGER NOT NULL, --versjon
                                            gjelder_fom          DATE NOT NULL DEFAULT now(),
                                            aktoer_ident              TEXT NOT NULL -- fødelsnummer/personIdent, orgnummer, ...
);

CREATE TABLE IF NOT EXISTS aktoer_audit (
                                            id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            aktoer_id                 BIGINT NOT NULL REFERENCES aktoer(id) DEFERRABLE NOT NULL,
                                            bruker                    TEXT NOT NULL, -- bruker eller system som gjør endringen
                                            tidspunkt_endret          TIMESTAMPTZ NOT NULL DEFAULT now(),
                                            informasjon               TEXT NOT NULL /* menneske-lesbar informasjon om hva slags endring som blir gjort. eks:
                                              endret fødselsnummer, nytt fødselsnummer gyldig fra <dato>
                                              aktør opprettet, årsak ...
                                              aktør merket for sletting ved <dato>, årsak ...
                                              */
);
