SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS skattekort_raw
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    aktoer_id                BIGINT REFERENCES aktoer(id) DEFERRABLE NOT NULL,
    body                     TEXT NOT NULL,
    dato_opprettet           TIMESTAMPTZ DEFAULT now()
);
