SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS bestilling
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    fnr                      CHAR(11) NOT NULL,
    inntektsaar              CHAR(4)  NOT NULL,
    skattekort_identifikator CHAR(38),
    dato_mottatt             DATE,
    dato_oppdatert           DATE,
    dato_abonnent            DATE,
    dato_sendt_abonnent      DATE,
    resultat_paa_foresporsel char(50),
    dato_returnert_os        DATE,
    data_mottatt             CHAR(50),
    erstattes_av_fnr         CHAR(11)     DEFAULT NULL,
    dato_opprettet           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
)