SET lock_timeout = '5s';

DROP INDEX IF EXISTS ix_fk_bestilling_id;
DROP TABLE IF EXISTS bestilling;

CREATE OR REPLACE FUNCTION update_dato_oppdatert_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.dato_oppdatert = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS bestillinger
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    aktoer_id                BIGINT REFERENCES aktoer(id) DEFERRABLE NOT NULL,
    fnr                      TEXT NOT NULL,
    aar                      TEXT NOT NULL,
    dato_oppdatert           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bestillinger_batch
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    bestilling_id            BIGINT REFERENCES bestillinger(id) DEFERRABLE NOT NULL,
    status                   TEXT NOT NULL DEFAULT 'NY',
    bestillingsreferanse     TEXT NULL DEFAULT NULL, -- referansenummer returnert fra skatt på bestillingskall
    dialogreferanse          TEXT NULL DEFAULT NULL, -- referanse til dialogporten. Denne er ikke planlagt brukt enda.
    dato_oppdatert           TIMESTAMPTZ DEFAULT now()
);

CREATE TRIGGER bestillinger_set_dato_oppdatert_on_insert_update
    BEFORE INSERT OR UPDATE ON bestillinger
    FOR EACH ROW
EXECUTE FUNCTION update_dato_oppdatert_column();

CREATE TRIGGER bestillinger_batch_set_dato_oppdatert_on_insert_update
    BEFORE INSERT OR UPDATE ON bestillinger_batch
    FOR EACH ROW
EXECUTE FUNCTION update_dato_oppdatert_column();