SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS bestilling
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    fnr                      TEXT NOT NULL,
    inntektsaar              TEXT NOT NULL,
    skattekort_identifikator TEXT,
    dato_mottatt             DATE,
    dato_oppdatert           DATE,
    dato_abonnent            DATE,
    dato_sendt_abonnent      DATE,
    resultat_paa_foresporsel TEXT,
    dato_returnert_os        DATE,
    data_mottatt             TEXT,
    erstattes_av_fnr         TEXT     DEFAULT NULL,
    dato_opprettet           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)