SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS bestillinger_batch
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    status                   VARCHAR(10) NOT NULL DEFAULT 'NY',
    bestillingsreferanse     VARCHAR(20) NULL DEFAULT NULL, -- referansenummer returnert fra skatt på bestillingskall
    oppdatert                TIMESTAMPTZ DEFAULT now(),
    data_sendt               JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS bestillinger
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id                BIGINT REFERENCES person(id) DEFERRABLE NOT NULL,
    fnr                      VARCHAR(11) NOT NULL,
    aar                      SMALLINT NOT NULL,
    bestilling_batch_id      BIGINT REFERENCES bestillinger_batch(id) DEFERRABLE NULL,
    oppdatert                TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bestillinger_person_id ON bestillinger (person_id);
CREATE INDEX IF NOT EXISTS bestillinger_bestillinger_batch_id ON bestillinger (bestilling_batch_id);
CREATE UNIQUE INDEX IF NOT EXISTS bestillinger_fnr_aar_unique ON bestillinger (person_id, fnr, aar);
