set lock_timeout = '1s';
set statement_timeout = '5s';

CREATE TABLE IF NOT EXISTS bevis_sending (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    skattekort_id  BIGINT NOT NULL NOT NULL,
    forsystem      TEXT NOT NULL,
    sending        TEXT NOT NULL,
    fnr            TEXT NOT NULL,
    opprettet      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bevis_sending_fnr ON bevis_sending (fnr);
