SET lock_timeout = '5s';

-- Skattekort-tabellen er ment å være immuterbar. Om vi skal gjøre endringer er ideen at vi lager et helt nytt skattekort, med tilhørende
-- registrering i person_audit som beskriver hvorfor endringen ble gjort, link til sak, og hva slags endring som ble gjort
-- "Gyldig skattekort" for et år finnes ved WHERE inntektsaar = <> ORDER BY opprettet DESC LIMIT 1
-- Vi må lagre tidligere skattekort for supportformål. Vi bruker også fjorårets skattekort for utregninger i noen få tilfeller.
CREATE TABLE IF NOT EXISTS skattekort
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id     BIGINT REFERENCES personer (id) DEFERRABLE          NOT NULL,

    utstedt_dato  DATE                                                NOT NULL,
    identifikator TEXT                                                NOT NULL,
    inntektsaar   SMALLINT                                            NOT NULL,
    kilde         TEXT                                                NOT NULL, -- 'skatt', 'syntetisert', 'manuelt' for ekte skattekort, syntetiske skattekort med default skattesatser, manuelt justerte skattekort
    opprettet     TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS skattekort_person_id ON skattekort (person_id);

CREATE TABLE IF NOT EXISTS skattekort_del
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    skattekort_id        BIGINT REFERENCES skattekort (id) DEFERRABLE        NOT NULL,

    trekk_kode           TEXT                                                NOT NULL, -- 'PENSJON', 'PENSJON_FRA_NAV', 'LOENN_FRA_NAV', 'LOENN_FRA_BIARBEIDSGIVER', 'LOENN_FRA_HOVEDARBEIDSGIVER'
    type                 TEXT                                                NOT NULL, -- 'frikort', 'tabell', 'prosent'
    frikort_beloep       INT                                                 NULL,     -- null for ikke-frikort
    tabell_nummer        TEXT                                                NULL,     -- null for ikke-tabellkort
    prosentsats          DECIMAL(5, 2)                                       NULL,     -- null for frikort, satt for prosent og tabell. Kan være desimaltall for kildeskattytere. yttrykker marginalprosent for tabellkort
    antall_mnd_for_trekk DECIMAL(3, 1)                                       NULL      -- null for frikort, typisk 12 eller 10.5
);
CREATE INDEX IF NOT EXISTS skattekort_del_skattekort_id ON skattekort_del (skattekort_id);

CREATE TABLE IF NOT EXISTS skattekort_tilleggsopplysning
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    skattekort_id BIGINT REFERENCES skattekort (id) DEFERRABLE        NOT NULL,

    opplysning    TEXT                                                NOT NULL -- 'kildeskattPaaPensjon', 'kildeskattPaaLoenn' etc
);
CREATE INDEX IF NOT EXISTS skattekort_tilleggsopplysing_skattekort_id ON skattekort_tilleggsopplysning (skattekort_id);
CREATE UNIQUE INDEX IF NOT EXISTS skattekort_tilleggsopplysing_skattekort_id_opplysning ON skattekort_tilleggsopplysning (skattekort_id, opplysning);

CREATE TABLE IF NOT EXISTS skattekort_data
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id    BIGINT REFERENCES personer (id) DEFERRABLE          NOT NULL,
    inntektsaar  SMALLINT                                            NOT NULL,
    data_mottatt TEXT                                                NOT NULL,
    opprettet    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS skattekort_data_person_id ON skattekort_data (person_id);
