SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS skattekort_data
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id                BIGINT REFERENCES person(id) DEFERRABLE NOT NULL,
    data_mottatt             TEXT NOT NULL,
    opprettet                TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS skattekort_data_person_id ON skattekort_data (person_id);
