set lock_timeout = '1s';
set statement_timeout = '5s';

CREATE TABLE IF NOT EXISTS forespoersel_input -- tabell for å "leke" at vi mottar meldinger fra MQ
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    forsystem TEXT NOT NULL,
    inntektsaar SMALLINT NOT NULL,
    fnr TEXT NOT NULL
);