SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS aktoer (
                                      id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                      flagget                   BOOLEAN
);

CREATE TABLE IF NOT EXISTS aktoer_offnr (
                                            id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            aktoer_id                 BIGINT NOT NULL REFERENCES aktoer(id) DEFERRABLE NOT NULL,
                                            lopenr                    INTEGER NOT NULL, --versjon
                                            dato_gjelder_fom          DATE NOT NULL DEFAULT now(),
                                            aktoer_ident              TEXT NOT NULL -- fødelsnummer/personIdent, ...
);

CREATE TABLE IF NOT EXISTS aktoer_audit (
                                            id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            aktoer_id                 BIGINT NOT NULL REFERENCES aktoer(id) DEFERRABLE NOT NULL,
                                            bruker                    TEXT NOT NULL, -- bruker eller system som gjør endringen
                                            tidspunkt_endret          TIMESTAMPTZ NOT NULL DEFAULT now(),
                                            tag                       TEXT NULL, -- maskinlesbar tag for å kunne filtrere i visning av auditlogg, type "MOTTATT_BESTILLING"
                                            informasjon               TEXT NOT NULL /* menneske-lesbar informasjon om hva slags endring som blir gjort. eks:
                                              endret fødselsnummer, nytt fødselsnummer gyldig fra <dato>
                                              aktør opprettet, årsak ...
                                              aktør merket for sletting ved <dato>, årsak ...
                                              */
);

CREATE TABLE IF NOT EXISTS aktoer_bestiltfra (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    aktoer_id               BIGINT NOT NULL REFERENCES aktoer(id) DEFERRABLE NOT NULL,
    aar                     SMALLINT NOT NULL, -- årstall for bestilling
    bestiller               TEXT NOT NULL -- arena, oppdragz etc. Må sammenfalle med kode slik at vi trigger riktig utsendelsesintegrasjon
);

