SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS forespoersel
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    data_mottatt             TEXT NOT NULL,
    forsystem                VARCHAR(10) NOT NULL,
    opprettet                TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS forespoersel_forsystem ON forespoersel(forsystem);

CREATE TABLE IF NOT EXISTS forespoersel_skattekort
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    forespoersel_id          BIGINT NOT NULL REFERENCES forespoersel(id) DEFERRABLE NOT NULL,
    aar                      SMALLINT NOT NULL,
    fnr                      VARCHAR(11) NOT NULL
);
CREATE INDEX IF NOT EXISTS forespoersel_skattekort_aar_fnr ON forespoersel_skattekort(aar, fnr);

CREATE TABLE IF NOT EXISTS person_bestiltfra (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id               BIGINT NOT NULL REFERENCES person(id) DEFERRABLE NOT NULL,
    aar                     SMALLINT NOT NULL, -- årstall for bestilling
    forsystem               TEXT NOT NULL -- arena, oppdragz etc. Må sammenfalle med kode slik at vi trigger riktig utsendelsesintegrasjon
    );
