SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS personer
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    flagget BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS foedselsnumre
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id   BIGINT                                              NOT NULL REFERENCES personer (id) DEFERRABLE NOT NULL,
    gjelder_fom DATE                                                NOT NULL DEFAULT now(),
    fnr         TEXT                                                NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS foedselsnumre_person_id ON foedselsnumre (person_id);

CREATE TABLE IF NOT EXISTS forespoersler
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    data_mottatt TEXT                                                NOT NULL,
    forsystem    TEXT                                                NOT NULL,
    opprettet    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS forespoersler_forsystem ON forespoersler (forsystem);

CREATE TABLE IF NOT EXISTS abonnementer
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    forespoersel_id BIGINT                                              NOT NULL REFERENCES forespoersler (id) DEFERRABLE NOT NULL,
    person_id       BIGINT                                              NOT NULL REFERENCES personer (id) DEFERRABLE NOT NULL,
    inntektsaar     SMALLINT                                            NOT NULL
);
CREATE INDEX IF NOT EXISTS abonnement_aar_fnr ON abonnementer (inntektsaar, person_id);

CREATE TABLE IF NOT EXISTS utsendinger
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    abonnement_id BIGINT                                              NOT NULL REFERENCES abonnementer (id) DEFERRABLE NOT NULL,
    fnr           TEXT                                                NOT NULL,
    forsystem     TEXT                                                NOT NULL,
    inntektsaar   SMALLINT                                            NOT NULL,
    opprettet     TIMESTAMPTZ                                         NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS utsendinger_foedselsnummer ON utsendinger (fnr);

CREATE TABLE IF NOT EXISTS person_audit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id   BIGINT                                              NOT NULL REFERENCES personer (id) DEFERRABLE NOT NULL,
    bruker_id   TEXT                                                NOT NULL, -- bruker eller system som gjør endringen
    opprettet   TIMESTAMPTZ                                         NOT NULL DEFAULT now(),
    tag         TEXT                                                NULL,     -- maskinlesbar tag for å kunne filtrere i visning av auditlogg, type "MOTTATT_BESTILLING"
    informasjon TEXT                                                NOT NULL /* menneske-lesbar informasjon om hva slags endring som blir gjort. eks:
                                              endret fødselsnummer, nytt fødselsnummer gyldig fra <dato>
                                              aktør opprettet, årsak ...
                                              aktør merket for sletting ved <dato>, årsak ...
                                              skattekort sendt arena ..
                                              */
);
CREATE INDEX IF NOT EXISTS person_audit_person_id ON person_audit (person_id);

CREATE TABLE IF NOT EXISTS bestillingsbatcher
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    status               TEXT                                                NOT NULL DEFAULT 'NY',
    bestillingsreferanse TEXT                                                NULL     DEFAULT NULL, -- referansenummer returnert fra skatt på bestillingskall
    oppdatert            TIMESTAMPTZ                                                  DEFAULT now(),
    data_sendt           TEXT                                                NOT NULL
);

CREATE TABLE IF NOT EXISTS bestillinger
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  NOT NULL,
    person_id           BIGINT REFERENCES personer (id) DEFERRABLE           NOT NULL,
    fnr                 TEXT                                                 NOT NULL,
    inntektsaar         SMALLINT                                             NOT NULL,
    bestillingsbatch_id BIGINT REFERENCES bestillingsbatcher (id) DEFERRABLE NULL,
    oppdatert           TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bestillinger_person_id ON bestillinger (person_id);
CREATE INDEX IF NOT EXISTS bestillinger_bestillingsbatch_id ON bestillinger (bestillingsbatch_id);
CREATE UNIQUE INDEX IF NOT EXISTS foedsselsnumre_aar_unique ON bestillinger (person_id, fnr, inntektsaar);

