SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS person
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    flagget BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS person_fnr
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id   BIGINT                                              NOT NULL REFERENCES person (id) DEFERRABLE NOT NULL,
    gjelder_fom DATE                                                NOT NULL DEFAULT now(),
    fnr         TEXT                                                NOT NULL -- fødelsnummer/personIdent, ...
);

CREATE TABLE IF NOT EXISTS person_audit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id   BIGINT                                              NOT NULL REFERENCES person (id) DEFERRABLE NOT NULL,
    bruker_id   TEXT                                                NOT NULL, -- bruker eller system som gjør endringen
    opprettet   TIMESTAMPTZ                                         NOT NULL DEFAULT now(),
    tag         TEXT                                                NULL,     -- maskinlesbar tag for å kunne filtrere i visning av auditlogg, type "MOTTATT_BESTILLING"
    informasjon TEXT                                                NOT NULL /* menneske-lesbar informasjon om hva slags endring som blir gjort. eks:
                                              endret fødselsnummer, nytt fødselsnummer gyldig fra <dato>
                                              aktør opprettet, årsak ...
                                              aktør merket for sletting ved <dato>, årsak ...
                                              skattekort sendt arena ..
                                              */
);

CREATE INDEX IF NOT EXISTS person_fnr_person_id ON person_fnr (person_id);
CREATE INDEX IF NOT EXISTS person_audit_person_id ON person_audit (person_id);

CREATE TABLE IF NOT EXISTS bestillinger_batch
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    status               TEXT                                                NOT NULL DEFAULT 'NY',
    bestillingsreferanse TEXT                                                NULL     DEFAULT NULL, -- referansenummer returnert fra skatt på bestillingskall
    oppdatert            TIMESTAMPTZ                                                  DEFAULT now(),
    data_sendt           JSON                                                NOT NULL
);

CREATE TABLE IF NOT EXISTS bestillinger
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  NOT NULL,
    person_id           BIGINT REFERENCES person (id) DEFERRABLE             NOT NULL,
    fnr                 TEXT                                                 NOT NULL,
    aar                 SMALLINT                                             NOT NULL,
    bestilling_batch_id BIGINT REFERENCES bestillinger_batch (id) DEFERRABLE NULL,
    oppdatert           TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bestillinger_person_id ON bestillinger (person_id);
CREATE INDEX IF NOT EXISTS bestillinger_bestillinger_batch_id ON bestillinger (bestilling_batch_id);
CREATE UNIQUE INDEX IF NOT EXISTS bestillinger_fnr_aar_unique ON bestillinger (person_id, fnr, aar);

CREATE TABLE IF NOT EXISTS skattekort_data
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id    BIGINT REFERENCES person (id) DEFERRABLE            NOT NULL,
    data_mottatt TEXT                                                NOT NULL,
    opprettet    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS skattekort_data_person_id ON skattekort_data (person_id);

CREATE TABLE IF NOT EXISTS forespoersel
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    data_mottatt TEXT                                                NOT NULL,
    forsystem    TEXT                                                NOT NULL,
    opprettet    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS forespoersel_forsystem ON forespoersel (forsystem);

CREATE TABLE IF NOT EXISTS forespoersel_skattekort
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    forespoersel_id BIGINT                                              NOT NULL REFERENCES forespoersel (id) DEFERRABLE NOT NULL,
    aar             SMALLINT                                            NOT NULL,
    fnr             TEXT                                                NOT NULL
);
CREATE INDEX IF NOT EXISTS forespoersel_skattekort_aar_fnr ON forespoersel_skattekort (aar, fnr);

CREATE TABLE IF NOT EXISTS person_bestiltfra
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id BIGINT                                              NOT NULL REFERENCES person (id) DEFERRABLE NOT NULL,
    aar       SMALLINT                                            NOT NULL, -- årstall for bestilling
    forsystem TEXT                                                NOT NULL  -- arena, oppdragz etc. Må sammenfalle med kode slik at vi trigger riktig utsendelsesintegrasjon
);
