name: Squawk DB migration lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/main/resources/db/migration/*.sql'

jobs:
  squawk-db-migration-lint:
    permissions:
      contents: read
      pull-requests: write
    name: Run DB migration lint
    uses: navikt/mob-gha-workflows/.github/workflows/squawk-migration-lint.yaml@dac7a1ac47e76110d90af301b2152057c215c867 # ratchet:navikt/mob-gha-workflows/.github/workflows/squawk-migration-lint.yaml@v1.0.0
